github: [quertenmont]
polar: quertenmont
ko_fi: quertenmont
liberapay: quertenmont
tidelift: pypi/django-sequencefield
custom: ["https://www.buymeacoffee.com/quertenmont", "https://www.paypal.com/donate/?business=JQ7Y92B9BTCGE&no_recurring=0&currency_code=EUR"]
